### PR TITLE
Add parallel testing from non-TP threads

### PR DESCRIPTION
**Pull request by stephentoub**
Adds a very simple scheduler that's used for the initial round of queues from ParallelTestAsync.  That way, we can see the impact when the test is started from non-ThreadPool threads in addition to when it's started from ThreadPool threads.

### CODE REVIEW

**Comment by benaadams** [comment]
Thank you :)

**Comment by benaadams** [comment]
Oh my days... is this still measuring the same thing? Just upgraded to 2.0 https://github.com/benaadams/ThreadPoolTaskTesting/pull/2 to look at new TP changes 

And the results are crazy high compared to before!

Last time I ran it (6 months ago) - 4 core no HT
```
                                                                       Parallelism
                            Serial          2x         16x         64x        512x
QUWI No Queues             11.065 M    10.939 M    10.258 M    12.078 M    12.581 M
- Depth    2                9.903 M     8.503 M     9.129 M     9.345 M     9.706 M
- Depth   16               10.144 M     9.990 M    10.221 M    10.138 M    10.046 M
- Depth   64                9.911 M    10.285 M    10.337 M    10.403 M    10.360 M
- Depth  512               10.066 M    10.138 M    10.434 M    10.408 M    10.309 M
```
Now with RuntimeFrameworkVersion 2.0.0-beta-001499-00
```
                                  Serial          2x         16x         64x        512x
QUWI No Queues (TP)             12.860 M    12.767 M    10.328 M    13.200 M    17.453 M
- Depth    2                    38.468 M    32.386 M    35.551 M    32.791 M    38.516 M
- Depth   16                   292.951 M   181.377 M   104.145 M   277.477 M   203.832 M
- Depth   64                     1.031 B   154.045 M   986.728 M   908.771 M   370.972 M
- Depth  512                     4.958 B     4.746 B     3.846 B     2.283 B   709.994 M

QUWI No Queues                  16.544 M    14.962 M     2.697 M     7.515 M     6.416 M
- Depth    2                    39.215 M    15.653 M     4.302 M    11.929 M     6.201 M
- Depth   16                   238.436 M    81.647 M    65.293 M    36.815 M     8.880 M
- Depth   64                   673.823 M   329.021 M    51.301 M    44.790 M     5.583 M
- Depth  512                     3.868 B     3.376 B   190.643 M    44.013 M     5.570 M
```

**Comment by benaadams** [comment]
Can't see anything in tests that should have effected it; so maybe the threadpool changes are just that good?

**Comment by stephentoub** [comment]
> Can't see anything in tests that should have effected it

Did you try reverting https://github.com/benaadams/ThreadPoolTaskTesting/pull/1?

> so maybe the threadpool changes are just that good?

I was expecting them to be very good, e.g. I saw 2-5x improvements on many of the tests I ran on various machines.  200-400x is more than I was expecting, but if that's really true, hey, I'll take it ;)

**Comment by benaadams** [comment]
Hmm.. stranger have 2.0.0-alpha-004775 installed, so don't event think I have the changes

Ah, removing the PR it drops to expected ish (lots of stuff running at this point so not valid numbers)
```
                                                                        Parallelism
                             Serial          2x         16x         64x        512x
QUWI No Queues             10.414 M     9.015 M     6.607 M     9.690 M    10.374 M
- Depth    2                7.146 M     7.002 M     6.936 M     7.151 M     7.083 M
- Depth   16                7.905 M     7.150 M     7.971 M     8.262 M     8.756 M
- Depth   64                8.829 M     8.261 M     8.350 M     8.552 M     8.999 M
- Depth  512                9.150 M     8.755 M     8.628 M     8.935 M     9.138 M
```
Will have a dig

**Comment by stephentoub** [comment]
Ok. It's quite possible I messed up the test change somehow; obviously feel free to pull it out in your repo.

FYI, I've been using this simple test to get a read on throughput through the global queue:
```C#
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;

class Program
{
    static void Main()
    {
        int numWorkers = Environment.ProcessorCount;
        var counts = new StrongBox<long>[numWorkers];

        WaitCallback worker = null;
        worker = s =>
        {
            ((StrongBox<long>)s).Value++;
            ThreadPool.QueueUserWorkItem(worker, s);
        };

        for (int i = 0; i < numWorkers; i++)
        {
            counts[i] = new StrongBox<long>();
            ThreadPool.QueueUserWorkItem(worker, counts[i]);
        }

        long lastCount = counts.Sum(s => s.Value);
        while (true)
        {
            Thread.Sleep(1000);
            long curCount = counts.Sum(s => s.Value);
            Console.WriteLine($"Requests / sec: {curCount - lastCount}");
            lastCount = curCount;
        }
    }
}
```

**Comment by benaadams** [comment]
Its just one tweak that does it. Changing Task.Run from lamba to Action causes the huge increase.
e.g.
```csharp
Task.Run(() => testAsync(depth, subCount))
```
to
```csharp
Action body = () => testAsync(depth, subCount);
Task.Run(body);
``` 
Not entirely sure why

**Comment by benaadams** [comment]
Unless the lamba (closure) becomes hoisted with the Action; but is recaptured each time without?

**Comment by stephentoub** [comment]
The task returned from testAsync gets ignored when the lambda is cast to Action.

**Comment by benaadams** [comment]
Ah, so it isn't testing how long to execute. Changing to `Func<Task>` restores the previous behaviour; seems queueing is pretty fast :)

**Pull request merged**
